Scenario:
  # - { path: $(find-pkg-share scenario_test_runner)/scenario/collision.yaml }
  # - { path: $(find-pkg-share scenario_test_runner)/scenario/distance-condition.yaml }
  # - { path: $(find-pkg-share scenario_test_runner)/scenario/success.yaml, expect: success }
  - path: $(find-pkg-share scenario_test_runner)/scenario/ControllerAction.AssignControllerAction.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/LongitudinalAction.SpeedAction.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/Property.isBlind.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/all-in-one.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/minimal.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/prefixed-name-reference.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/stand-still.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/failure.yaml
    expect: failure
