Scenario:
  # - { path: $(find-pkg-share scenario_test_runner)/scenario/collision.yaml }
  # - { path: $(find-pkg-share scenario_test_runner)/scenario/distance-condition.yaml }
  # - { path: $(find-pkg-share scenario_test_runner)/scenario/success.yaml}
  - path: $(find-pkg-share scenario_test_runner)/scenario/ByEntityCondition.EntityCondition.DistanceCondition.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/ByEntityCondition.EntityCondition.RelativeDistanceCondition.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/ControllerAction.AssignControllerAction.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/LongitudinalAction.SpeedAction.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/Property.isBlind.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/RoutingAction.FollowTrajectoryAction-star.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/RoutingAction.FollowTrajectoryAction-straight.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/RoutingAction.FollowTrajectoryAction-zero-distance.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/all-in-one.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/minimal.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/prefixed-name-reference.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/stand-still.yaml
