name: Interface update notification
on:
  pull_request_target:
    paths:
      - openscenario/openscenario_interpreter_msgs/msg/*.msg
      - simulation/traffic_simulator_msgs/msg/*.msg

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: master # Ensure we are on the master branch, because the PR may be from a fork, which may contains malicious code.
      - name: Add label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "interface breaking"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "This PR may breaks the interface to external services! Please see https://tier4.atlassian.net/wiki/spaces/S/pages/1984987364"
          message-id: "interface-breaking-notification"
