name: Post check list
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, labeled, edited]
jobs:
  post_check_list:
    name: Post check list
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            # Checklist for reviewers ☑️
            All references to "You" in the following text refer to the code reviewer.
            - [ ] Is this pull request written in a way that is easy to read from a third-party perspective?
            - [ ] Is there sufficient information (background, purpose, specification, algorithm description, list of disruptive changes, and migration guide) in the description of this pull request?
            - [ ] If this pull request contains a destructive change, does this pull request contain the migration guide?
            - [ ] Labels of this pull request are valid?
            - [ ] All unit tests/integration tests are included in this pull request? If you think adding test cases is unnecessary, please describe why and cross out this line.
            - [ ] The documentation for this pull request is enough? If you think adding documents for this pull request is unnecessary, please describe why and cross out this line.
          message-id: 'post-check-list'
