name: SpellCheckAll

on:
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve spell check dictionary
        run: |
          curl --silent --show-error \
            --output .github/workflows/autoware.json \
            https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json

      - name: Merge words array
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq -n ''{ words: [ inputs.words ] | add }'' .github/workflows/autoware.json .github/workflows/custom_spell.json > .github/workflows/words.json'

      - name: Merge config
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq -s ''add'' .github/workflows/autoware.json .github/workflows/words.json > .github/workflows/.cspell.json'

      - uses: streetsidesoftware/cspell-action@v1
        with:
          files: |
             **/*.{c,cpp,h,hpp,xml,yaml,yml,md,txt,sh,repos,py}
          config: ".github/workflows/.cspell.json"
          incremental_files_only: false
          strict: true
