name: SpellCheck

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve spell check dictionary
        run: |
          curl --silent --show-error \
            --output .github/workflows/.cspell.json \
            https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json

      - uses: streetsidesoftware/cspell-action@v1.2.3
        with:
          config: ".github/workflows/.cspell.json"
          incremental_files_only: false
          strict: false
