name: Tool dispatch
on:
  pull_request:
    types: [labeled]

jobs:
  make_dispatch_event:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'wait for regression test'
    steps:
    - name: trigger
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/tier4/sim_evaluation_tools/dispatches \
          -d '{"event_type":"pull_request_notification","client_payload":{"branch_name":"${{ github.event.pull_request.head.ref }}","pr_number":"${{ github.event.pull_request.number }}"}}'
